"""
STRATA Industrial Materials & Hardeners Seed Database
Contains 105+ verified industrial, aerospace, and natural materials with full ASTM standards,
thermomechanical parameters, and curing agent systems.
"""

from typing import List, Dict, Any

SEED_MATERIALS: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. AEROSPACE & INDUSTRIAL CARBON FIBRES (Continuous Reinforcements)
    # =========================================================================
    {
        "id": "toray_t300",
        "name": "Toray T300 Carbon Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.76,
        "E": 230.0,
        "ts": 3530.0,
        "elong": 1.5,
        "k": 10.5,
        "cte": -0.4,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 22.0,
        "costHi": 35.0,
        "source": "Standard modulus PAN precursor carbonized at 1300°C (Toray Composite Materials)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "The baseline aerospace structural carbon fiber. Standard 3K/6K/12K tow with 40+ years flight heritage.",
        "nu": 0.20,
        "color": "#141414",
        "astm": "ASTM D4018 (Carbon fiber tow tensile), ASTM D3822"
    },
    {
        "id": "toray_t700s",
        "name": "Toray T700S High-Strength Carbon",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.80,
        "E": 230.0,
        "ts": 4900.0,
        "elong": 2.1,
        "k": 9.4,
        "cte": -0.4,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 28.0,
        "costHi": 45.0,
        "source": "High-strain PAN fiber optimized for pressure vessels and structural aerospace laminates",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Industry standard for hydrogen/CNG composite pressure vessels (COPVs), sporting goods, and wind turbine spars.",
        "nu": 0.20,
        "color": "#1c1c1c",
        "astm": "ASTM D4018 (tensile properties of carbon fiber tows)"
    },
    {
        "id": "toray_t800s",
        "name": "Toray T800S Intermediate Modulus",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.80,
        "E": 294.0,
        "ts": 5880.0,
        "elong": 2.0,
        "k": 11.2,
        "cte": -0.5,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 45.0,
        "costHi": 70.0,
        "source": "Intermediate modulus (IM) fiber used in Boeing 787 and Airbus A350 primary airframe structure",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Higher stiffness-to-weight with extreme tensile strength. The premier commercial jet wing/fuselage reinforcement.",
        "nu": 0.20,
        "color": "#181a1c",
        "astm": "ASTM D4018, SACMA SRM 16R-94"
    },
    {
        "id": "toray_t1000g",
        "name": "Toray T1000G Ultra-High-Strength",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.80,
        "E": 294.0,
        "ts": 6370.0,
        "elong": 2.2,
        "k": 12.0,
        "cte": -0.55,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 90.0,
        "costHi": 150.0,
        "source": "World record commercial tensile strength carbon fiber (Toray Advanced Composites)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "Highest tensile strength carbon fiber commercially manufactured. Critical for rocket motor cases and deep-submergence hulls.",
        "nu": 0.20,
        "color": "#0d0f12",
        "astm": "ASTM D4018 (ultra-high strength classification)"
    },
    {
        "id": "toray_m40j",
        "name": "Toray M40J High Modulus Carbon",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.77,
        "E": 377.0,
        "ts": 4400.0,
        "elong": 1.2,
        "k": 18.0,
        "cte": -0.8,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 120.0,
        "costHi": 200.0,
        "source": "Graphitized PAN precursor fiber heat-treated to >2500°C for satellite reflector trusses",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "High modulus class. Balances 377 GPa stiffness with 4400 MPa strength for space satellite structures.",
        "nu": 0.20,
        "color": "#111417",
        "astm": "ASTM D4018, ASTM D3552"
    },
    {
        "id": "toray_m60j",
        "name": "Toray M60J Ultra-High Modulus Carbon",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.93,
        "E": 588.0,
        "ts": 3920.0,
        "elong": 0.7,
        "k": 25.0,
        "cte": -1.1,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 250.0,
        "costHi": 450.0,
        "source": "Ultra-high modulus graphitized fiber for dimensionally stable space optics and telescopes",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Exceptional stiffness (almost 3x steel). Brittle, extremely low CTE. Used in space telescope metering trusses.",
        "nu": 0.20,
        "color": "#0a0c0e",
        "astm": "ASTM D4018, ESA PSS-01-704"
    },
    {
        "id": "hexcel_as4",
        "name": "Hexcel HexTow AS4 Carbon Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.79,
        "E": 231.0,
        "ts": 4413.0,
        "elong": 1.8,
        "k": 11.0,
        "cte": -0.6,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 26.0,
        "costHi": 40.0,
        "source": "Continuous polyacrylonitrile (PAN) based fiber (Hexcel Corporation)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Classic military and commercial aerospace workhorse. Excellent shear bonding with epoxy matrices.",
        "nu": 0.20,
        "color": "#171717",
        "astm": "ASTM D4018, MIL-HDBK-17"
    },
    {
        "id": "hexcel_im7",
        "name": "Hexcel HexTow IM7 Intermediate Modulus",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.78,
        "E": 276.0,
        "ts": 5654.0,
        "elong": 1.9,
        "k": 12.5,
        "cte": -0.5,
        "maxT": 400.0,
        "procT": None,
        "elec": "C",
        "costLo": 50.0,
        "costHi": 85.0,
        "source": "Hexcel intermediate-modulus PAN fiber, aerospace primary structure baseline",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Selected for primary aircraft structures including the F-35 Lightning II wing skins and missile bodies.",
        "nu": 0.20,
        "color": "#121314",
        "astm": "ASTM D4018, BMS 8-276 baseline"
    },
    {
        "id": "pitch_k13d2u",
        "name": "Granoc K13D2U Pitch Carbon Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.20,
        "E": 935.0,
        "ts": 3600.0,
        "elong": 0.4,
        "k": 800.0,
        "cte": -1.45,
        "maxT": 500.0,
        "procT": None,
        "elec": "C",
        "costLo": 400.0,
        "costHi": 700.0,
        "source": "Meso-phase pitch precursor pyrolyzed and graphitized at 3000°C (Nippon Graphite Fiber)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Thermal conductivity of 800 W/m·K (2x copper!) with 935 GPa modulus. Ultimate thermal management fiber.",
        "nu": 0.20,
        "color": "#060708",
        "astm": "ASTM D4018, ASTM E1461 (laser flash)"
    },

    # =========================================================================
    # 2. HIGH-PERFORMANCE GLASS & CERAMIC FIBRES
    # =========================================================================
    {
        "id": "eglass",
        "name": "E-Glass Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.58,
        "E": 76.0,
        "ts": 3400.0,
        "elong": 4.8,
        "k": 1.3,
        "cte": 5.4,
        "maxT": 550.0,
        "procT": None,
        "elec": "I",
        "costLo": 1.5,
        "costHi": 3.0,
        "source": "Alumino-borosilicate glass melt drawn through platinum bushings",
        "moist": "M",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "The global composites workhorse (90% of all fiber volume). High strength, low cost, non-conductive.",
        "nu": 0.22,
        "color": "#e9e6dc",
        "astm": "ASTM D2343 (yarn tensile), ASTM D578"
    },
    {
        "id": "sglass",
        "name": "S-2 Glass Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.49,
        "E": 87.0,
        "ts": 4590.0,
        "elong": 5.7,
        "k": 1.35,
        "cte": 5.1,
        "maxT": 700.0,
        "procT": None,
        "elec": "I",
        "costLo": 5.0,
        "costHi": 12.0,
        "source": "High-purity magnesium aluminosilicate glass (AGY Holding Corp)",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": False,
        "note": "35% higher tensile strength and 20% higher stiffness than E-glass. Standard for helicopter rotor blades and armor.",
        "nu": 0.22,
        "color": "#ded9ce",
        "astm": "ASTM D2343, MIL-C-60346"
    },
    {
        "id": "quartzfiber",
        "name": "Quartz Fibre (Fused SiO₂)",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.20,
        "E": 72.0,
        "ts": 3400.0,
        "elong": 5.0,
        "k": 1.4,
        "cte": 0.54,
        "maxT": 1050.0,
        "procT": None,
        "elec": "I",
        "costLo": 30.0,
        "costHi": 80.0,
        "source": "99.99% pure synthetic fused quartz crystal redraw (Saint-Gobain Quartz)",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "Lowest dielectric loss and near-zero thermal expansion. Essential for supersonic stealth radomes.",
        "nu": 0.17,
        "color": "#f0ece0",
        "astm": "ASTM D2343, ASTM D257"
    },
    {
        "id": "nextel_312",
        "name": "3M Nextel 312 Ceramic Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.70,
        "E": 150.0,
        "ts": 1700.0,
        "elong": 1.1,
        "k": 3.0,
        "cte": 3.0,
        "maxT": 1200.0,
        "procT": None,
        "elec": "I",
        "costLo": 150.0,
        "costHi": 280.0,
        "source": "Alumina-boria-silica sol-gel continuous filament (3M Advanced Materials)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Retains strength to 1200°C continuously. Used on NASA space shuttle TPS thermal blankets and jet seals.",
        "nu": 0.22,
        "color": "#e3e3e0",
        "astm": "ASTM C1275, ASTM C1359"
    },
    {
        "id": "nextel_440",
        "name": "3M Nextel 440 Ceramic Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 3.05,
        "E": 190.0,
        "ts": 2000.0,
        "elong": 1.0,
        "k": 3.5,
        "cte": 5.3,
        "maxT": 1400.0,
        "procT": None,
        "elec": "I",
        "costLo": 220.0,
        "costHi": 380.0,
        "source": "Aluminosilicate sol-gel ceramic continuous filament with gamma-alumina phase",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Higher modulus and heat resistance than Nextel 312; low creep to 1400°C in ceramic matrix composites.",
        "nu": 0.23,
        "color": "#dedbd5",
        "astm": "ASTM C1359, ASTM C1161"
    },
    {
        "id": "basalt",
        "name": "Basalt Continuous Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.70,
        "E": 90.0,
        "ts": 4100.0,
        "elong": 3.15,
        "k": 0.035,
        "cte": 8.0,
        "maxT": 600.0,
        "procT": None,
        "elec": "I",
        "costLo": 2.0,
        "costHi": 4.0,
        "source": "Molten mined basalt volcanic rock extruded through platinum-rhodium bushings",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "Eco-friendly natural mineral replacement for glass fiber with superior temperature and chemical resistance.",
        "nu": 0.25,
        "color": "#2f2f31",
        "astm": "ASTM D3822, ASTM D2343"
    },
    {
        "id": "boron",
        "name": "CVD Boron Fibre (on W core)",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.57,
        "E": 400.0,
        "ts": 3600.0,
        "elong": 0.8,
        "k": 38.0,
        "cte": 4.5,
        "maxT": 2000.0,
        "procT": None,
        "elec": "S",
        "costLo": 500.0,
        "costHi": 1000.0,
        "source": "CVD reduction of BCl3 with H2 onto a 12-micron tungsten wire filament (Specialty Materials Inc)",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "World's highest compressive strength fiber. Unmatched resistance to microbuckling in B/Al and B/Epoxy.",
        "nu": 0.21,
        "color": "#4a4a4a",
        "astm": "ASTM D3552, ASTM D3822"
    },
    {
        "id": "sic_fiber",
        "name": "Hi-Nicalon SiC Ceramic Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 2.74,
        "E": 270.0,
        "ts": 2800.0,
        "elong": 1.0,
        "k": 7.8,
        "cte": 3.5,
        "maxT": 1400.0,
        "procT": None,
        "elec": "S",
        "costLo": 800.0,
        "costHi": 1400.0,
        "source": "Pyrolysis of polycarbosilane precursor cured by electron beam (NGS Advanced Fibers)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "The premier continuous fiber for SiC/SiC ceramic matrix composites in jet engine turbine shrouds.",
        "nu": 0.20,
        "color": "#28292b",
        "astm": "ASTM C1275, ASTM C1359"
    },

    # =========================================================================
    # 3. HIGH-PERFORMANCE ARAMIDS, UHMWPE & LIQUID CRYSTAL FIBRES
    # =========================================================================
    {
        "id": "kevlar_29",
        "name": "DuPont Kevlar 29 Aramid",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.44,
        "E": 70.0,
        "ts": 3600.0,
        "elong": 3.6,
        "k": 0.04,
        "cte": -2.0,
        "maxT": 400.0,
        "procT": None,
        "elec": "I",
        "costLo": 18.0,
        "costHi": 30.0,
        "source": "Poly-para-phenylene terephthalamide solution spun (DuPont Protection Technologies)",
        "moist": "M",
        "uv": "H",
        "chem": "G",
        "tough": "H",
        "ductile": False,
        "note": "The original ballistic grade. High elongation to failure absorbs extreme impact energy in helmets and armor.",
        "nu": 0.36,
        "color": "#d4aa2e",
        "astm": "ASTM D885, NIJ Standard 0101.06"
    },
    {
        "id": "kevlar_49",
        "name": "DuPont Kevlar 49 Structural Aramid",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.44,
        "E": 112.0,
        "ts": 3600.0,
        "elong": 2.4,
        "k": 0.04,
        "cte": -4.0,
        "maxT": 400.0,
        "procT": None,
        "elec": "I",
        "costLo": 24.0,
        "costHi": 40.0,
        "source": "Heat-treated Kevlar yarn with aligned molecular orientation for structural composites",
        "moist": "M",
        "uv": "H",
        "chem": "G",
        "tough": "H",
        "ductile": False,
        "note": "Higher modulus structural grade. Used extensively in marine racing hulls, kayaks, aircraft fairings.",
        "nu": 0.36,
        "color": "#c9a227",
        "astm": "ASTM D885, ASTM D3822"
    },
    {
        "id": "kevlar_149",
        "name": "DuPont Kevlar 149 Ultra-High Modulus",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.47,
        "E": 179.0,
        "ts": 3450.0,
        "elong": 1.9,
        "k": 0.05,
        "cte": -5.0,
        "maxT": 400.0,
        "procT": None,
        "elec": "I",
        "costLo": 55.0,
        "costHi": 95.0,
        "source": "Highest orientation para-aramid fiber engineered for maximum axial stiffness",
        "moist": "L",
        "uv": "H",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "40% stiffer than Kevlar 49 with lowest moisture regain of all aramids (1.2%).",
        "nu": 0.36,
        "color": "#b89420",
        "astm": "ASTM D885, ASTM D7264"
    },
    {
        "id": "dyneema_sk75",
        "name": "Dyneema SK75 UHMWPE Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 0.97,
        "E": 120.0,
        "ts": 3400.0,
        "elong": 3.5,
        "k": 20.0,
        "cte": -12.0,
        "maxT": 140.0,
        "procT": None,
        "elec": "I",
        "costLo": 25.0,
        "costHi": 45.0,
        "source": "Gel-spun ultra-high molecular weight polyethylene (DSM Dyneema / Avient)",
        "moist": "L",
        "uv": "M",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "Floats on water (density 0.97). 15x stronger than steel on weight basis. Severe low melting point limitation (144°C).",
        "nu": 0.46,
        "color": "#f2f0eb",
        "astm": "ASTM D885, MIL-STD-662F"
    },
    {
        "id": "dyneema_sk99",
        "name": "Dyneema SK99 Ultra-Grade UHMWPE",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 0.97,
        "E": 155.0,
        "ts": 4000.0,
        "elong": 3.2,
        "k": 22.0,
        "cte": -12.0,
        "maxT": 140.0,
        "procT": None,
        "elec": "I",
        "costLo": 50.0,
        "costHi": 90.0,
        "source": "Next-generation gel-spun UHMWPE fiber with highest strength-to-weight ratio",
        "moist": "L",
        "uv": "M",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "State-of-the-art ballistic protection and America's Cup high-performance composite rigging.",
        "nu": 0.46,
        "color": "#faf8f2",
        "astm": "ASTM D885, VPAM ballistic"
    },
    {
        "id": "pbo_zylon",
        "name": "PBO Fibre (Zylon AS)",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.56,
        "E": 270.0,
        "ts": 5800.0,
        "elong": 2.5,
        "k": 0.04,
        "cte": -6.0,
        "maxT": 650.0,
        "procT": None,
        "elec": "I",
        "costLo": 60.0,
        "costHi": 120.0,
        "source": "Dry-jet wet spinning of poly(p-phenylene-2,6-benzobisoxazole) (Toyobo)",
        "moist": "H",
        "uv": "H",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "World record organic tensile strength (5.8 GPa). Severe photodegradation in UV requires black coating.",
        "nu": 0.22,
        "color": "#d4cc8e",
        "astm": "ASTM D885, FIA 8860-2018"
    },
    {
        "id": "vectran",
        "name": "Vectran LCP Fibre",
        "cat": "synfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.40,
        "E": 75.0,
        "ts": 3200.0,
        "elong": 3.8,
        "k": 0.04,
        "cte": -2.0,
        "maxT": 250.0,
        "procT": None,
        "elec": "I",
        "costLo": 35.0,
        "costHi": 65.0,
        "source": "Melt-spun aromatic polyester liquid-crystal polymer (Kuraray)",
        "moist": "L",
        "uv": "M",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "Zero moisture absorption and virtually no creep. Famous for NASA Mars Pathfinder landing airbags.",
        "nu": 0.35,
        "color": "#c4af78",
        "astm": "ASTM D885, ASTM D3822"
    },

    # =========================================================================
    # 4. INDUSTRIAL RESINS & THERMOSET MATRICES
    # =========================================================================
    {
        "id": "epoxy",
        "name": "Standard DGEBA Epoxy Resin",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.20,
        "E": 3.5,
        "ts": 80.0,
        "elong": 4.0,
        "k": 0.20,
        "cte": 60.0,
        "maxT": 150.0,
        "procT": 120.0,
        "elec": "I",
        "costLo": 3.0,
        "costHi": 8.0,
        "source": "Diglycidyl ether of bisphenol A (DGEBA) prepolymer",
        "moist": "M",
        "uv": "M",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "The baseline structural thermoset matrix for carbon and glass fiber composites worldwide.",
        "nu": 0.35,
        "color": "#e0c98a",
        "astm": "ASTM D638, ASTM D792, ASTM D3418"
    },
    {
        "id": "epoxy_cycom",
        "name": "CYCOM 977-3 Toughened Epoxy",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.28,
        "E": 3.7,
        "ts": 105.0,
        "elong": 5.2,
        "k": 0.22,
        "cte": 45.0,
        "maxT": 180.0,
        "procT": 180.0,
        "elec": "I",
        "costLo": 45.0,
        "costHi": 80.0,
        "source": "Thermoplastic-toughened 180°C curing aerospace prepreg epoxy (Solvay Composite Materials)",
        "moist": "L",
        "uv": "M",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "Industry gold standard for compression-after-impact (CAI) performance in primary flight structures.",
        "nu": 0.36,
        "color": "#c7b275",
        "astm": "ASTM D638, ASTM D7137, BMS 8-276"
    },
    {
        "id": "bmi",
        "name": "Cytec 5250-4 Bismaleimide (BMI)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.30,
        "E": 3.8,
        "ts": 75.0,
        "elong": 2.2,
        "k": 0.22,
        "cte": 40.0,
        "maxT": 240.0,
        "procT": 190.0,
        "elec": "I",
        "costLo": 40.0,
        "costHi": 75.0,
        "source": "Thermosetting addition polyimide resin for high temperature supersonic airframes",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Bridges gap between epoxy and polyimide. Used in F-22 and F/A-18 supersonic skins reaching 200°C+.",
        "nu": 0.35,
        "color": "#b8a06e",
        "astm": "ASTM D638, SACMA SRM 1R-94"
    },
    {
        "id": "cyest",
        "name": "TenCate EX-1515 Cyanate Ester",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.22,
        "E": 3.2,
        "ts": 85.0,
        "elong": 3.0,
        "k": 0.18,
        "cte": 35.0,
        "maxT": 250.0,
        "procT": 180.0,
        "elec": "I",
        "costLo": 50.0,
        "costHi": 95.0,
        "source": "Cyanate ester resin engineered for satellite radomes, antennas, and cryogenic tanks",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Ultra-low outgassing (CVCM < 0.01%), exceptionally low moisture uptake (<0.8%), low dielectric loss.",
        "nu": 0.36,
        "color": "#ddd4b8",
        "astm": "ASTM D638, ASTM E595"
    },
    {
        "id": "phenolic",
        "name": "Phenolic Novolac Resin (FST)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.25,
        "E": 4.0,
        "ts": 55.0,
        "elong": 1.5,
        "k": 0.20,
        "cte": 65.0,
        "maxT": 200.0,
        "procT": 160.0,
        "elec": "I",
        "costLo": 2.0,
        "costHi": 4.5,
        "source": "Phenol-formaldehyde condensation resin with low smoke emission additives",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Unrivalled Fire, Smoke, and Toxicity (FST) performance. Mandatory for commercial aircraft cabin interiors.",
        "nu": 0.35,
        "color": "#382414",
        "astm": "ASTM D638, FAR 25.853, ASTM E662"
    },
    {
        "id": "vinylester",
        "name": "Vinyl Ester Resin (Derakane 411)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.15,
        "E": 3.4,
        "ts": 82.0,
        "elong": 5.0,
        "k": 0.20,
        "cte": 70.0,
        "maxT": 130.0,
        "procT": 25.0,
        "elec": "I",
        "costLo": 3.0,
        "costHi": 6.0,
        "source": "Epoxy-backbone esterified with methacrylic acid (Ashland / INEOS)",
        "moist": "L",
        "uv": "M",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Superior resistance to blistering, acids, and seawater osmosis. Standard for chemical tanks and marine hulls.",
        "nu": 0.35,
        "color": "#e3dcc0",
        "astm": "ASTM D638, ASTM C581"
    },
    {
        "id": "polyester",
        "name": "Unsaturated Polyester Resin",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.20,
        "E": 3.3,
        "ts": 60.0,
        "elong": 2.0,
        "k": 0.17,
        "cte": 100.0,
        "maxT": 100.0,
        "procT": 20.0,
        "elec": "I",
        "costLo": 1.5,
        "costHi": 3.0,
        "source": "Ortho- or isophthalic acid reacted with glycols and styrene monomer",
        "moist": "H",
        "uv": "M",
        "chem": "F",
        "tough": "L",
        "ductile": False,
        "note": "Cheapest common matrix. Widely used for boat hulls, bathtubs, and automotive body panels.",
        "nu": 0.37,
        "color": "#e6e0c9",
        "astm": "ASTM D638, ASTM D2584"
    },
    {
        "id": "pu",
        "name": "Polyurethane Resin (Rigid)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.20,
        "E": 1.0,
        "ts": 40.0,
        "elong": 300.0,
        "k": 0.25,
        "cte": 150.0,
        "maxT": 100.0,
        "procT": 100.0,
        "elec": "I",
        "costLo": 2.0,
        "costHi": 4.0,
        "source": "Polyol reacted with diisocyanate",
        "moist": "M",
        "uv": "H",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "High impact toughness, abrasion resistance, and flexible vibration absorption.",
        "nu": 0.45,
        "color": "#e6dcc8",
        "astm": "ASTM D638"
    },
    {
        "id": "silicone",
        "name": "Silicone Rubber Elastomer",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.10,
        "E": 0.05,
        "ts": 7.0,
        "elong": 400.0,
        "k": 0.20,
        "cte": 300.0,
        "maxT": 300.0,
        "procT": 150.0,
        "elec": "I",
        "costLo": 5.0,
        "costHi": 12.0,
        "source": "Polymerized siloxane monomers derived from silica",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": True,
        "note": "Widest service temperature range of any elastomer (-60°C to +300°C).",
        "nu": 0.47,
        "color": "#e6e3dc",
        "astm": "ASTM D412, ASTM D638"
    },

    # =========================================================================
    # 5. HIGH-PERFORMANCE ENGINEERING THERMOPLASTICS
    # =========================================================================
    {
        "id": "peek",
        "name": "Victrex PEEK 450G",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.30,
        "E": 4.0,
        "ts": 100.0,
        "elong": 45.0,
        "k": 0.25,
        "cte": 47.0,
        "maxT": 260.0,
        "procT": 380.0,
        "elec": "I",
        "costLo": 65.0,
        "costHi": 110.0,
        "source": "Semi-crystalline polyether ether ketone (Victrex plc)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Elite thermoplastic matrix. Recyclable, weldable, infinite shelf-life prepreg, continuous 260°C use.",
        "nu": 0.38,
        "color": "#c9a876",
        "astm": "ASTM D638, ASTM D3418, ASTM F2026"
    },
    {
        "id": "pekk",
        "name": "Arkema Kepstan PEKK",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.31,
        "E": 4.2,
        "ts": 110.0,
        "elong": 35.0,
        "k": 0.26,
        "cte": 42.0,
        "maxT": 270.0,
        "procT": 360.0,
        "elec": "I",
        "costLo": 75.0,
        "costHi": 130.0,
        "source": "Polyetherketoneketone engineered with controlled crystallization rate (Arkema)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Higher compressive strength and lower processing temperature than PEEK. Ideal for automated fiber placement (AFP).",
        "nu": 0.38,
        "color": "#d0b080",
        "astm": "ASTM D638, FAR 25.853"
    },
    {
        "id": "pps",
        "name": "Celanese Fortron PPS",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.35,
        "E": 3.6,
        "ts": 85.0,
        "elong": 15.0,
        "k": 0.28,
        "cte": 50.0,
        "maxT": 220.0,
        "procT": 310.0,
        "elec": "I",
        "costLo": 12.0,
        "costHi": 25.0,
        "source": "Semi-crystalline polyphenylene sulfide engineering polymer",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": True,
        "note": "Inherently flame-retardant (UL94 V-0) and completely insoluble in all known solvents below 200°C.",
        "nu": 0.37,
        "color": "#c4a068",
        "astm": "ASTM D638, ASTM D792, UL 94"
    },
    {
        "id": "pei_ultem",
        "name": "SABIC Ultem 1000 (PEI)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.27,
        "E": 3.2,
        "ts": 105.0,
        "elong": 60.0,
        "k": 0.22,
        "cte": 56.0,
        "maxT": 170.0,
        "procT": 340.0,
        "elec": "I",
        "costLo": 15.0,
        "costHi": 30.0,
        "source": "Amorphous polyetherimide high-heat resin (SABIC)",
        "moist": "M",
        "uv": "M",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Exceptional dielectric stability, flame retardancy (limiting oxygen index 47%), and high ductile strength.",
        "nu": 0.36,
        "color": "#c28830",
        "astm": "ASTM D638, FAR 25.853"
    },
    {
        "id": "pi_kapton",
        "name": "Polyimide (PI / Kapton-type)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.42,
        "E": 3.0,
        "ts": 230.0,
        "elong": 7.0,
        "k": 0.37,
        "cte": 20.0,
        "maxT": 300.0,
        "procT": 350.0,
        "elec": "I",
        "costLo": 50.0,
        "costHi": 100.0,
        "source": "Condensation polymerization of dianhydride and diamine monomers",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Among the highest-performance polymer matrices. Spacecraft thermal blankets and flex circuits.",
        "nu": 0.34,
        "color": "#e0a838",
        "astm": "ASTM D638, ASTM D792"
    },
    {
        "id": "ptfe",
        "name": "PTFE (Teflon)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 2.20,
        "E": 0.5,
        "ts": 25.0,
        "elong": 300.0,
        "k": 0.25,
        "cte": 112.0,
        "maxT": 260.0,
        "procT": 380.0,
        "elec": "I",
        "costLo": 8.0,
        "costHi": 20.0,
        "source": "Polymerization of tetrafluoroethylene (TFE) gas from fluorspar",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": True,
        "note": "Lowest friction coefficient (~0.04) of any solid; self-lubricating bearing composite matrix.",
        "nu": 0.46,
        "color": "#f2f0f0",
        "astm": "ASTM D638, ASTM D792"
    },
    {
        "id": "hdpe",
        "name": "High-Density Polyethylene (HDPE)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 0.95,
        "E": 1.0,
        "ts": 30.0,
        "elong": 800.0,
        "k": 0.44,
        "cte": 120.0,
        "maxT": 80.0,
        "procT": 160.0,
        "elec": "I",
        "costLo": 1.0,
        "costHi": 2.0,
        "source": "Ziegler–Natta catalysis of ethylene gas",
        "moist": "L",
        "uv": "H",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Tough, chemical-resistant matrix for wood-plastic composites (WPC) and pipe.",
        "nu": 0.46,
        "color": "#eeeade",
        "astm": "ASTM D638, ASTM D792"
    },
    {
        "id": "pc",
        "name": "Polycarbonate (PC)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.20,
        "E": 2.4,
        "ts": 65.0,
        "elong": 130.0,
        "k": 0.20,
        "cte": 65.0,
        "maxT": 130.0,
        "procT": 280.0,
        "elec": "I",
        "costLo": 2.5,
        "costHi": 4.5,
        "source": "Bisphenol-A polycondensation with phosgene",
        "moist": "M",
        "uv": "M",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Optically clear, impact-resistant thermoplastic used for helmet visors and aircraft canopies.",
        "nu": 0.38,
        "color": "#e8e4f0",
        "astm": "ASTM D638, ASTM D792"
    },
    {
        "id": "pet",
        "name": "Polyethylene Terephthalate (PET)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.38,
        "E": 3.1,
        "ts": 80.0,
        "elong": 300.0,
        "k": 0.24,
        "cte": 70.0,
        "maxT": 80.0,
        "procT": 260.0,
        "elec": "I",
        "costLo": 1.5,
        "costHi": 3.0,
        "source": "Condensation of terephthalic acid and ethylene glycol",
        "moist": "M",
        "uv": "M",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Common thermoplastic; widely recycled and used as matrix in structural core foams.",
        "nu": 0.41,
        "color": "#e8e4dc",
        "astm": "ASTM D638, ASTM D792"
    },
    {
        "id": "nylon6",
        "name": "Nylon 6 (Polyamide 6)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.14,
        "E": 2.8,
        "ts": 75.0,
        "elong": 150.0,
        "k": 0.25,
        "cte": 90.0,
        "maxT": 120.0,
        "procT": 250.0,
        "elec": "I",
        "costLo": 2.5,
        "costHi": 4.5,
        "source": "Ring-opening polymerization of caprolactam",
        "moist": "H",
        "uv": "M",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Tough thermoplastic matrix. Absorbs atmospheric moisture up to 3% which drops modulus.",
        "nu": 0.39,
        "color": "#e9dfc0",
        "astm": "ASTM D638, ASTM D789"
    },
    {
        "id": "pp",
        "name": "Polypropylene (Isotactic)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 0.91,
        "E": 1.5,
        "ts": 35.0,
        "elong": 150.0,
        "k": 0.22,
        "cte": 120.0,
        "maxT": 100.0,
        "procT": 200.0,
        "elec": "I",
        "costLo": 1.1,
        "costHi": 2.2,
        "source": "Ziegler-Natta polymerized propylene monomer",
        "moist": "L",
        "uv": "H",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Lowest density common thermoplastic. Used in glass-mat thermoplastics (GMT) for automotive front-end modules.",
        "nu": 0.42,
        "color": "#eae6da",
        "astm": "ASTM D638, ASTM D1238"
    },

    # =========================================================================
    # 6. STRUCTURAL SANDWICH CORES
    # =========================================================================
    {
        "id": "nomex_honeycomb",
        "name": "Hexcel Nomex Honeycomb (HRH-10)",
        "cat": "core",
        "matrix": False,
        "reinf": True,
        "rho": 0.048,
        "E": 0.13,
        "ts": 2.2,
        "elong": 3.0,
        "k": 0.03,
        "cte": 15.0,
        "maxT": 180.0,
        "procT": None,
        "elec": "I",
        "costLo": 60.0,
        "costHi": 120.0,
        "source": "Aramid fiber paper dipped in heat-resistant phenolic resin (Hexcel)",
        "moist": "M",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": False,
        "note": "The premier aerospace sandwich core. Extremely high specific shear stiffness and strength in aircraft floors.",
        "nu": 0.40,
        "color": "#d6af58",
        "astm": "ASTM C365, ASTM C273, ASTM C393"
    },
    {
        "id": "alu_honeycomb",
        "name": "Aluminium 5052 Aerospace Honeycomb",
        "cat": "core",
        "matrix": False,
        "reinf": True,
        "rho": 0.050,
        "E": 0.95,
        "ts": 4.5,
        "elong": 5.0,
        "k": 1.8,
        "cte": 23.0,
        "maxT": 200.0,
        "procT": None,
        "elec": "C",
        "costLo": 25.0,
        "costHi": 50.0,
        "source": "Expanded 5052-H39 aluminum alloy foil bonded with structural adhesive",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "High-crush energy absorption, high operating temperature, non-flammable, excellent radio frequency shielding.",
        "nu": 0.33,
        "color": "#b8bcbd",
        "astm": "ASTM C365, MIL-STD-401"
    },
    {
        "id": "rohacell_71",
        "name": "Evonik Rohacell 71 IG-F PMI Foam",
        "cat": "core",
        "matrix": False,
        "reinf": True,
        "rho": 0.075,
        "E": 0.092,
        "ts": 2.8,
        "elong": 9.0,
        "k": 0.031,
        "cte": 36.0,
        "maxT": 190.0,
        "procT": None,
        "elec": "I",
        "costLo": 80.0,
        "costHi": 150.0,
        "source": "100% closed-cell polymethacrylimide (PMI) structural foam (Evonik Industries)",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "Withstands 180°C / 7 bar autoclave prepreg processing without cell collapse. Standard in helicopter blades.",
        "nu": 0.30,
        "color": "#f0ede1",
        "astm": "ASTM C273, ASTM D1621"
    },
    {
        "id": "balsa_core",
        "name": "Baltek End-Grain Balsa Wood",
        "cat": "core",
        "matrix": False,
        "reinf": True,
        "rho": 0.15,
        "E": 3.7,
        "ts": 13.0,
        "elong": 1.5,
        "k": 0.065,
        "cte": 60.0,
        "maxT": 120.0,
        "procT": None,
        "elec": "I",
        "costLo": 5.0,
        "costHi": 12.0,
        "source": "Kiln-dried natural balsa wood harvested with grain aligned through thickness (3A Composites)",
        "moist": "H",
        "uv": "M",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Naturally occurring honeycomb structure. Outstanding shear stiffness for mega wind-turbine blades.",
        "nu": 0.23,
        "color": "#ebd8b0",
        "astm": "ASTM C273, ASTM C365"
    },

    # =========================================================================
    # 7. INDUSTRIAL METALS & SUPERALLOYS (MMC Matrix & Structure)
    # =========================================================================
    {
        "id": "ti6al4v",
        "name": "Titanium Ti-6Al-4V (Grade 5)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 4.43,
        "E": 114.0,
        "ts": 950.0,
        "elong": 14.0,
        "k": 6.7,
        "cte": 8.6,
        "maxT": 400.0,
        "procT": 1650.0,
        "elec": "C",
        "costLo": 25.0,
        "costHi": 40.0,
        "source": "Alpha-beta titanium alloy, vacuum arc remelted",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Workhorse aerospace titanium. Used as MMC matrix with SiC fibers for jet compressor blings.",
        "nu": 0.31,
        "color": "#8f9092",
        "astm": "ASTM B348, ASTM E8/E8M, AMS 4928"
    },
    {
        "id": "ti6al4v_eli",
        "name": "Ti-6Al-4V ELI (Grade 23 Medical)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 4.43,
        "E": 112.0,
        "ts": 860.0,
        "elong": 16.0,
        "k": 6.7,
        "cte": 8.6,
        "maxT": 400.0,
        "procT": 1650.0,
        "elec": "C",
        "costLo": 35.0,
        "costHi": 60.0,
        "source": "Extra Low Interstitial (ELI) titanium alloy for cryogenic and medical implants",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Reduced oxygen content raises fracture toughness. The standard for orthopedic implants and space propellant tanks.",
        "nu": 0.31,
        "color": "#9ca0a6",
        "astm": "ASTM F136, ASTM E8/E8M"
    },
    {
        "id": "inconel_718",
        "name": "Special Metals Inconel 718",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.19,
        "E": 200.0,
        "ts": 1240.0,
        "elong": 20.0,
        "k": 11.4,
        "cte": 13.0,
        "maxT": 650.0,
        "procT": 1350.0,
        "elec": "C",
        "costLo": 40.0,
        "costHi": 65.0,
        "source": "Precipitation-hardenable nickel-chromium superalloy with niobium",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Dominant jet engine superalloy. Exceptional creep-rupture strength up to 650°C and cryogenic toughness.",
        "nu": 0.29,
        "color": "#8a8d7f",
        "astm": "ASTM B637, AMS 5662"
    },
    {
        "id": "inconel_625",
        "name": "Special Metals Inconel 625",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.44,
        "E": 205.0,
        "ts": 930.0,
        "elong": 40.0,
        "k": 9.8,
        "cte": 12.8,
        "maxT": 980.0,
        "procT": 1320.0,
        "elec": "C",
        "costLo": 45.0,
        "costHi": 70.0,
        "source": "Solid-solution strengthened nickel-chromium-molybdenum alloy",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Virtually immune to pitting, crevice corrosion, and chloride stress-corrosion cracking in subsea environments.",
        "nu": 0.31,
        "color": "#848a80",
        "astm": "ASTM B446, ASTM E8/E8M"
    },
    {
        "id": "hastelloy_c276",
        "name": "Haynes Hastelloy C-276",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.89,
        "E": 205.0,
        "ts": 790.0,
        "elong": 60.0,
        "k": 10.2,
        "cte": 11.2,
        "maxT": 1000.0,
        "procT": 1370.0,
        "elec": "C",
        "costLo": 50.0,
        "costHi": 85.0,
        "source": "Ni-Mo-Cr superalloy with tungsten additions (Haynes International)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "The most universally corrosion-resistant alloy known. Resists wet chlorine gas, hypochlorite, and chlorine dioxide.",
        "nu": 0.30,
        "color": "#7a8276",
        "astm": "ASTM B574, ASTM E8/E8M"
    },
    {
        "id": "al7075_t6",
        "name": "Aluminium 7075-T6 Aerospace",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 2.81,
        "E": 71.0,
        "ts": 570.0,
        "elong": 11.0,
        "k": 130.0,
        "cte": 23.4,
        "maxT": 120.0,
        "procT": 480.0,
        "elec": "C",
        "costLo": 4.5,
        "costHi": 7.5,
        "source": "Zinc-magnesium-copper precipitation-hardened wrought alloy",
        "moist": "L",
        "uv": "L",
        "chem": "F",
        "tough": "M",
        "ductile": True,
        "note": "High-strength aircraft aluminum comparable in yield strength to mild structural steel.",
        "nu": 0.33,
        "color": "#b8bcc0",
        "astm": "ASTM B221, ASTM B209, AMS 4045"
    },
    {
        "id": "al2024_t3",
        "name": "Aluminium 2024-T3 Airframe",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 2.78,
        "E": 73.0,
        "ts": 480.0,
        "elong": 18.0,
        "k": 121.0,
        "cte": 23.2,
        "maxT": 120.0,
        "procT": 490.0,
        "elec": "C",
        "costLo": 4.0,
        "costHi": 6.5,
        "source": "Copper-alloyed aerospace aluminum sheet and plate",
        "moist": "L",
        "uv": "L",
        "chem": "P",
        "tough": "H",
        "ductile": True,
        "note": "Supreme fatigue crack growth resistance. Standard for commercial jet lower wing skins.",
        "nu": 0.33,
        "color": "#bcc0c4",
        "astm": "ASTM B209, AMS 4037"
    },
    {
        "id": "alsi10mg",
        "name": "AlSi10Mg (Additive AM Alloy)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 2.68,
        "E": 68.0,
        "ts": 410.0,
        "elong": 7.0,
        "k": 140.0,
        "cte": 21.0,
        "maxT": 150.0,
        "procT": 600.0,
        "elec": "C",
        "costLo": 30.0,
        "costHi": 60.0,
        "source": "Gas atomized spherical metal powder for laser powder bed fusion (LPBF)",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": True,
        "note": "Most common metal 3D printing alloy. Near-eutectic Al-Si composition gives low thermal shrinkage.",
        "nu": 0.33,
        "color": "#a8acaf",
        "astm": "ASTM F3318, ASTM E8/E8M"
    },
    {
        "id": "ss_17_4ph",
        "name": "Stainless Steel 17-4 PH (H900)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 7.80,
        "E": 196.0,
        "ts": 1310.0,
        "elong": 10.0,
        "k": 17.8,
        "cte": 10.8,
        "maxT": 315.0,
        "procT": 1040.0,
        "elec": "C",
        "costLo": 6.0,
        "costHi": 12.0,
        "source": "Martensitic precipitation-hardening chromium-nickel-copper steel",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Combines high strength and hardness with corrosion resistance superior to 400-series stainless.",
        "nu": 0.27,
        "color": "#9ca2a8",
        "astm": "ASTM A564, AMS 5643"
    },
    {
        "id": "nitinol",
        "name": "Nitinol 55 (Shape Memory NiTi)",
        "cat": "metal",
        "matrix": True,
        "reinf": True,
        "rho": 6.45,
        "E": 75.0,
        "ts": 890.0,
        "elong": 15.0,
        "k": 18.0,
        "cte": 11.0,
        "maxT": 300.0,
        "procT": 1310.0,
        "elec": "C",
        "costLo": 80.0,
        "costHi": 180.0,
        "source": "Near-equiatomic nickel-titanium alloy, vacuum induction melted",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Superelasticity (8% recoverable strain) and thermal shape memory. Used as SMA wire actuators embedded in composite panels.",
        "nu": 0.33,
        "color": "#6d7885",
        "astm": "ASTM F2063, ASTM E8/E8M"
    },
    {
        "id": "invar",
        "name": "Invar 36 (Fe-Ni Zero-Expansion)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.05,
        "E": 148.0,
        "ts": 490.0,
        "elong": 40.0,
        "k": 10.5,
        "cte": 1.2,
        "maxT": 250.0,
        "procT": 1430.0,
        "elec": "C",
        "costLo": 20.0,
        "costHi": 40.0,
        "source": "36% nickel iron controlled expansion alloy",
        "moist": "M",
        "uv": "L",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Uniquely low CTE (1.2×10⁻⁶/K) closely matches carbon fiber composites. Mandatory for aerospace composite curing molds.",
        "nu": 0.29,
        "color": "#6a6b6c",
        "astm": "ASTM F1684, ASTM E228"
    },
    {
        "id": "msteel300",
        "name": "Maraging Steel 300",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.00,
        "E": 190.0,
        "ts": 2000.0,
        "elong": 8.0,
        "k": 16.0,
        "cte": 10.2,
        "maxT": 400.0,
        "procT": 1450.0,
        "elec": "C",
        "costLo": 20.0,
        "costHi": 40.0,
        "source": "Vacuum induction melted; 18% Ni, Co, Mo, Ti alloying with ultra-low carbon",
        "moist": "L",
        "uv": "L",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Ultra-high-strength martensitic steel (ts = 2000 MPa) with high fracture toughness.",
        "nu": 0.30,
        "color": "#4a4b4d",
        "astm": "ASTM E8/E8M, AMS 6514"
    },
    {
        "id": "cube",
        "name": "Copper-Beryllium (CuBe2)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.25,
        "E": 131.0,
        "ts": 1380.0,
        "elong": 2.0,
        "k": 130.0,
        "cte": 17.5,
        "maxT": 300.0,
        "procT": 900.0,
        "elec": "C",
        "costLo": 50.0,
        "costHi": 100.0,
        "source": "Copper alloyed with 1.8–2.0% Be, precipitation age-hardened",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": False,
        "note": "Highest strength of any copper alloy; non-sparking tool material and precision spring.",
        "nu": 0.30,
        "color": "#c08040",
        "astm": "ASTM E8/E8M, ASTM B197"
    },

    # =========================================================================
    # 8. ADVANCED TECHNICAL CERAMICS & CMCs
    # =========================================================================
    {
        "id": "hexoloy_sic",
        "name": "Saint-Gobain Hexoloy SA SiC",
        "cat": "ceramic",
        "matrix": True,
        "reinf": True,
        "rho": 3.10,
        "E": 410.0,
        "ts": 460.0,
        "elong": 0.1,
        "k": 125.0,
        "cte": 4.0,
        "maxT": 1650.0,
        "procT": 2000.0,
        "elec": "S",
        "costLo": 25.0,
        "costHi": 60.0,
        "source": "Pressureless sintered alpha silicon carbide with no free silicon (Saint-Gobain)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Extreme hardness (2800 kg/mm² Knoop), high thermal conductivity, impervious to acid/alkali attack up to 1650°C.",
        "nu": 0.16,
        "color": "#2c2d30",
        "astm": "ASTM C1161, ASTM C1198"
    },
    {
        "id": "kyocera_sn282",
        "name": "Kyocera SN-282 Silicon Nitride",
        "cat": "ceramic",
        "matrix": True,
        "reinf": True,
        "rho": 3.20,
        "E": 310.0,
        "ts": 850.0,
        "elong": 0.25,
        "k": 30.0,
        "cte": 3.2,
        "maxT": 1400.0,
        "procT": 1800.0,
        "elec": "I",
        "costLo": 35.0,
        "costHi": 85.0,
        "source": "Gas-pressure sintered beta-Si3N4 with elongated interlocking grain microstructure",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Highest fracture toughness (KIc ~ 8 MPa·m½) among monolithic technical ceramics. Used in ceramic ball bearings and glow plugs.",
        "nu": 0.27,
        "color": "#404347",
        "astm": "ASTM C1161, ASTM C1421"
    },
    {
        "id": "alumina_995",
        "name": "Kyocera A-479 99.5% Alumina",
        "cat": "ceramic",
        "matrix": True,
        "reinf": True,
        "rho": 3.92,
        "E": 375.0,
        "ts": 380.0,
        "elong": 0.1,
        "k": 32.0,
        "cte": 8.0,
        "maxT": 1650.0,
        "procT": 1650.0,
        "elec": "I",
        "costLo": 6.0,
        "costHi": 15.0,
        "source": "Ultra-pure sintered alpha-Al2O3 calcined bauxite (Kyocera Fine Ceramics)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Standard high-purity electrical insulator substrate and wear-resistant tile.",
        "nu": 0.22,
        "color": "#ece8de",
        "astm": "ASTM C1161, ASTM C1198, ASTM D257"
    },
    {
        "id": "tosoh_zirconia",
        "name": "Tosoh 3Y-TZP Zirconia",
        "cat": "ceramic",
        "matrix": True,
        "reinf": True,
        "rho": 6.05,
        "E": 210.0,
        "ts": 1200.0,
        "elong": 0.6,
        "k": 2.2,
        "cte": 10.5,
        "maxT": 1200.0,
        "procT": 1500.0,
        "elec": "I",
        "costLo": 25.0,
        "costHi": 60.0,
        "source": "Tetragonal zirconia polycrystal stabilized with 3 mol% Y2O3 (Tosoh Corporation)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "Transformation-toughened ceramic. Stress-induced tetragonal-to-monoclinic phase shift stops crack growth (KIc > 10 MPa·m½).",
        "nu": 0.30,
        "color": "#f2eee9",
        "astm": "ASTM C1161, ISO 13356"
    },
    {
        "id": "b4c_armor",
        "name": "Ceradyne Boron Carbide (B₄C)",
        "cat": "ceramic",
        "matrix": False,
        "reinf": True,
        "rho": 2.52,
        "E": 460.0,
        "ts": 420.0,
        "elong": 0.1,
        "k": 35.0,
        "cte": 5.0,
        "maxT": 2000.0,
        "procT": None,
        "elec": "S",
        "costLo": 50.0,
        "costHi": 120.0,
        "source": "Hot-pressed boron carbide body armor tile (3M Ceradyne)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Third hardest material known (Vickers ~3000). The gold standard strike-face ceramic in lightweight personal ballistic plates.",
        "nu": 0.17,
        "color": "#1f1f21",
        "astm": "ASTM C1161, NIJ-0101.06"
    },
    {
        "id": "hfb2_uhtc",
        "name": "Hafnium Diboride (HfB₂ UHTC)",
        "cat": "ceramic",
        "matrix": True,
        "reinf": True,
        "rho": 11.20,
        "E": 530.0,
        "ts": 550.0,
        "elong": 0.1,
        "k": 105.0,
        "cte": 6.5,
        "maxT": 2500.0,
        "procT": 2200.0,
        "elec": "C",
        "costLo": 400.0,
        "costHi": 800.0,
        "source": "Ultra-High Temperature Ceramic (UHTC) synthesized via spark plasma sintering",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Melting point of 3380°C! The premier leading-edge material for hypersonic gliders (>Mach 5) encountering extreme aerothermal heating.",
        "nu": 0.15,
        "color": "#4a4b4e",
        "astm": "ASTM C1161, ASTM E1461"
    },
    {
        "id": "mullite",
        "name": "Mullite (3Al₂O₃·2SiO₂)",
        "cat": "ceramic",
        "matrix": True,
        "reinf": True,
        "rho": 3.17,
        "E": 220.0,
        "ts": 300.0,
        "elong": 0.2,
        "k": 6.0,
        "cte": 5.7,
        "maxT": 1700.0,
        "procT": 1840.0,
        "elec": "I",
        "costLo": 5.0,
        "costHi": 15.0,
        "source": "Fusion or sintering of alumina and silica at high temperature",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Excellent thermal shock resistance and creep stability at temperature; used as CMC matrix for thermal barrier coatings.",
        "nu": 0.27,
        "color": "#e0d9ca",
        "astm": "ASTM C1161, ASTM C373"
    },
    {
        "id": "cordierite",
        "name": "Cordierite Ceramic",
        "cat": "ceramic",
        "matrix": True,
        "reinf": False,
        "rho": 2.60,
        "E": 120.0,
        "ts": 100.0,
        "elong": 0.1,
        "k": 2.5,
        "cte": 1.5,
        "maxT": 1350.0,
        "procT": 1450.0,
        "elec": "I",
        "costLo": 3.0,
        "costHi": 10.0,
        "source": "Sintered from talc, clay, and alumina precursor powders at 1450°C",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Exceptionally low CTE (1.5×10⁻⁶/K) — extraordinary thermal shock resistance; catalytic converter honeycomb substrate.",
        "nu": 0.30,
        "color": "#d5cfc3",
        "astm": "ASTM C1161, ASTM C20"
    },
    {
        "id": "tic",
        "name": "Titanium Carbide (TiC)",
        "cat": "ceramic",
        "matrix": False,
        "reinf": True,
        "rho": 4.93,
        "E": 440.0,
        "ts": 200.0,
        "elong": 0.2,
        "k": 21.0,
        "cte": 7.4,
        "maxT": 2800.0,
        "procT": None,
        "elec": "C",
        "costLo": 15.0,
        "costHi": 40.0,
        "source": "Carbothermal reduction of TiO2 with carbon at 2000°C in vacuum",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Extremely hard (Vickers ~3000 HV); used in TiC/steel cermet cutting inserts.",
        "nu": 0.19,
        "color": "#2e2e30",
        "astm": "ASTM C1161"
    },

    # =========================================================================
    # 9. NANOMATERIALS & ADVANCED FILLERS
    # =========================================================================
    {
        "id": "tuball_swcnt",
        "name": "Tuball Single-Walled CNTs",
        "cat": "filler",
        "matrix": False,
        "reinf": True,
        "rho": 1.20,
        "E": 1050.0,
        "ts": 50000.0,
        "elong": 12.0,
        "k": 3500.0,
        "cte": -1.2,
        "maxT": 2000.0,
        "procT": None,
        "elec": "C",
        "costLo": 1000.0,
        "costHi": 3000.0,
        "source": "Continuous plasma-torch synthesized high-purity SWCNTs (OCSiAl)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": False,
        "note": "Ultra-low percolation threshold: just 0.01 wt% imparts antistatic/ESD properties to epoxy and thermoplastics.",
        "nu": 0.18,
        "color": "#050505",
        "astm": "ASTM D8281, ASTM D257"
    },
    {
        "id": "mwcnt",
        "name": "Multi-Walled Carbon Nanotubes",
        "cat": "filler",
        "matrix": False,
        "reinf": True,
        "rho": 1.40,
        "E": 900.0,
        "ts": 25000.0,
        "elong": 6.0,
        "k": 2000.0,
        "cte": -1.0,
        "maxT": 2000.0,
        "procT": None,
        "elec": "C",
        "costLo": 80.0,
        "costHi": 250.0,
        "source": "CVD fluidized-bed grown concentric cylindrical graphene tubes",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "M",
        "ductile": False,
        "note": "Imparts interlaminar fracture toughness (G1c) and electrical conductivity to carbon-fiber laminates at 0.5-2.0 wt%.",
        "nu": 0.20,
        "color": "#0d0d0d",
        "astm": "ASTM D8281, ASTM D5528"
    },
    {
        "id": "graphene_gnp",
        "name": "Graphene Nanoplatelets (GNP)",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 2.20,
        "E": 1000.0,
        "ts": 12000.0,
        "elong": 2.0,
        "k": 4000.0,
        "cte": -6.0,
        "maxT": 2000.0,
        "procT": None,
        "elec": "C",
        "costLo": 60.0,
        "costHi": 200.0,
        "source": "Thermally exfoliated expandable graphite (6-10 atomic layers thickness)",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "2D platelets provide massive barrier improvement against moisture and helium permeability while raising thermal conductivity.",
        "nu": 0.19,
        "color": "#111111",
        "astm": "ISO/TS 80004-13"
    },
    {
        "id": "mxene_ti3c2tx",
        "name": "Ti₃C₂Tₓ MXene Conductive Flakes",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 3.10,
        "E": 330.0,
        "ts": 550.0,
        "elong": 1.5,
        "k": 55.0,
        "cte": 8.0,
        "maxT": 800.0,
        "procT": None,
        "elec": "C",
        "costLo": 500.0,
        "costHi": 1500.0,
        "source": "HF/LiF etched MAX phase Ti3AlC2, delaminated into single-layer 2D sheets",
        "moist": "M",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "Record electromagnetic interference (EMI) shielding efficiency in ultra-thin composite films with metallic conductivity (>10,000 S/cm).",
        "nu": 0.22,
        "color": "#232b38",
        "astm": "ASTM D4935"
    },
    {
        "id": "hbn_powder",
        "name": "Hexagonal Boron Nitride (hBN)",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 2.10,
        "E": 100.0,
        "ts": 60.0,
        "elong": 0.1,
        "k": 60.0,
        "cte": 1.0,
        "maxT": 2000.0,
        "procT": None,
        "elec": "I",
        "costLo": 20.0,
        "costHi": 60.0,
        "source": "2D platelets of boron nitride, isoelectronic to graphene",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "'White graphene': highly thermally conductive (60 W/m·K) yet electrically insulating (breakdown strength >35 kV/mm). Key EV battery thermal filler.",
        "nu": 0.25,
        "color": "#f2f2f0",
        "astm": "ASTM D149, ASTM E1461"
    },
    {
        "id": "glass_microspheres",
        "name": "3M iM30K Hollow Glass Microspheres",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 0.60,
        "E": 1.2,
        "ts": 0.0,
        "elong": 0.0,
        "k": 0.12,
        "cte": 8.0,
        "maxT": 600.0,
        "procT": None,
        "elec": "I",
        "costLo": 4.0,
        "costHi": 9.0,
        "source": "Water-resistant chemically stable borosilicate glass hollow spheres (3M)",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Syntactic foam filler: isostatic crush strength of 30,000 psi (207 MPa). Reduces composite weight by up to 30%.",
        "nu": 0.30,
        "color": "#f8f8f8",
        "astm": "ASTM D3102, ASTM D2840"
    },
    {
        "id": "carbon_black",
        "name": "Conductive Carbon Black (Ketjenblack)",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 1.80,
        "E": 30.0,
        "ts": 0.0,
        "elong": 0.0,
        "k": 8.0,
        "cte": 2.0,
        "maxT": 1500.0,
        "procT": None,
        "elec": "C",
        "costLo": 5.0,
        "costHi": 15.0,
        "source": "High surface-area furnace black with branched porous chain morphology",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "L",
        "ductile": False,
        "note": "Percolation reached at only 1-3 wt%. Protects composite fuel lines and aircraft radomes from static buildup.",
        "nu": 0.20,
        "color": "#080808",
        "astm": "ASTM D1510, ASTM D2414, ASTM D257"
    },
    {
        "id": "silica",
        "name": "Fumed Silica Nanopowder",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 2.20,
        "E": 70.0,
        "ts": 20.0,
        "elong": 0.0,
        "k": 1.4,
        "cte": 0.5,
        "maxT": 1200.0,
        "procT": None,
        "elec": "I",
        "costLo": 2.0,
        "costHi": 5.0,
        "source": "Pyrogenic combustion of silicon tetrachloride vapour",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "A thickening/anti-sag filler and thixotropic agent in resins.",
        "nu": 0.17,
        "color": "#f0eee6",
        "astm": "ASTM C1274"
    },
    {
        "id": "nanoclay",
        "name": "Nanoclay (Montmorillonite)",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 2.60,
        "E": 170.0,
        "ts": 0.0,
        "elong": 0.0,
        "k": 0.3,
        "cte": 10.0,
        "maxT": 700.0,
        "procT": None,
        "elec": "I",
        "costLo": 2.0,
        "costHi": 6.0,
        "source": "Organically modified montmorillonite bentonite clay platelets",
        "moist": "M",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": False,
        "note": "Boosts barrier properties and fire retardancy at very low loadings (1-5%).",
        "nu": 0.25,
        "color": "#c9b896",
        "astm": "ASTM D7442"
    },
    {
        "id": "caco3",
        "name": "Calcium Carbonate (Precipitated)",
        "cat": "filler",
        "matrix": False,
        "reinf": False,
        "rho": 2.71,
        "E": 70.0,
        "ts": 0.0,
        "elong": 0.0,
        "k": 3.0,
        "cte": 25.0,
        "maxT": 800.0,
        "procT": None,
        "elec": "I",
        "costLo": 0.1,
        "costHi": 0.3,
        "source": "Mined limestone or chalk, ground to fine powder",
        "moist": "L",
        "uv": "L",
        "chem": "F",
        "tough": "L",
        "ductile": False,
        "note": "Cheapest bulking filler; reduces resin shrinkage and part cost.",
        "nu": 0.27,
        "color": "#f2f0e8",
        "astm": "ASTM D4218, ASTM C25"
    },

    # =========================================================================
    # 10. SUSTAINABLE NATURAL FIBRES & BIOPOLYMERS
    # =========================================================================
    {
        "id": "flax",
        "name": "European Flax Bast Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.50,
        "E": 60.0,
        "ts": 800.0,
        "elong": 2.4,
        "k": 0.05,
        "cte": 9.0,
        "maxT": 180.0,
        "procT": None,
        "elec": "I",
        "costLo": 1.8,
        "costHi": 3.5,
        "source": "Dew-retted stems of Linum usitatissimum, Western Europe",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "The stiffest commercial natural bast fiber. Outstanding vibration damping (3x better than carbon fiber).",
        "nu": 0.30,
        "color": "#d9cfa0",
        "astm": "ASTM D3822, ASTM D1577"
    },
    {
        "id": "hemp",
        "name": "Industrial Hemp Bast Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.48,
        "E": 35.0,
        "ts": 550.0,
        "elong": 2.0,
        "k": 0.05,
        "cte": 9.0,
        "maxT": 180.0,
        "procT": None,
        "elec": "I",
        "costLo": 1.2,
        "costHi": 2.5,
        "source": "Retted stalks of Cannabis sativa L.",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Rapidly renewable fiber. High specific strength used extensively in automotive interior compression molding.",
        "nu": 0.30,
        "color": "#c2b280",
        "astm": "ASTM D3822"
    },
    {
        "id": "jute",
        "name": "Jute Bast Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.30,
        "E": 30.0,
        "ts": 450.0,
        "elong": 1.8,
        "k": 0.05,
        "cte": 10.0,
        "maxT": 170.0,
        "procT": None,
        "elec": "I",
        "costLo": 0.4,
        "costHi": 0.9,
        "source": "Retted bark of Corchorus capsularis, South Asia",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Lowest cost natural textile reinforcement. Standard in low-cost automotive parcel shelves.",
        "nu": 0.30,
        "color": "#b89a5e",
        "astm": "ASTM D3822"
    },
    {
        "id": "kenaf",
        "name": "Kenaf Bast Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.45,
        "E": 40.0,
        "ts": 930.0,
        "elong": 3.0,
        "k": 0.04,
        "cte": 9.0,
        "maxT": 170.0,
        "procT": None,
        "elec": "I",
        "costLo": 0.3,
        "costHi": 0.8,
        "source": "Bast fibre retted from Hibiscus cannabinus stalks",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Stiff low-cost bast fibre; glass-fibre substitute with lower density.",
        "nu": 0.30,
        "color": "#c4a66a",
        "astm": "ASTM D3822, ASTM D1577"
    },
    {
        "id": "sisal",
        "name": "Sisal Leaf Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.45,
        "E": 22.0,
        "ts": 530.0,
        "elong": 3.0,
        "k": 0.04,
        "cte": 10.0,
        "maxT": 170.0,
        "procT": None,
        "elec": "I",
        "costLo": 0.4,
        "costHi": 0.9,
        "source": "Leaf fibre from Agave sisalana",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Widely used in ropes and twines; structural building panels.",
        "nu": 0.30,
        "color": "#d4c07a",
        "astm": "ASTM D3822"
    },
    {
        "id": "coir",
        "name": "Coir (Coconut) Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.15,
        "E": 6.0,
        "ts": 175.0,
        "elong": 30.0,
        "k": 0.05,
        "cte": 12.0,
        "maxT": 150.0,
        "procT": None,
        "elec": "I",
        "costLo": 0.2,
        "costHi": 0.5,
        "source": "Husk fibre from Cocos nucifera",
        "moist": "H",
        "uv": "M",
        "chem": "P",
        "tough": "H",
        "ductile": False,
        "note": "Lowest stiffness but highest elongation (30%) — high energy and sound absorption.",
        "nu": 0.30,
        "color": "#9a7c50",
        "astm": "ASTM D3822"
    },
    {
        "id": "ramie",
        "name": "Ramie Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.55,
        "E": 70.0,
        "ts": 900.0,
        "elong": 3.7,
        "k": 0.05,
        "cte": 8.0,
        "maxT": 180.0,
        "procT": None,
        "elec": "I",
        "costLo": 1.0,
        "costHi": 2.5,
        "source": "Bast fibre from Boehmeria nivea",
        "moist": "H",
        "uv": "M",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "One of the stiffest natural fibres with outstanding tensile strength.",
        "nu": 0.30,
        "color": "#e8dfc8",
        "astm": "ASTM D3822"
    },
    {
        "id": "pla",
        "name": "Polylactic Acid (PLA)",
        "cat": "synpoly",
        "matrix": True,
        "reinf": False,
        "rho": 1.24,
        "E": 3.5,
        "ts": 50.0,
        "elong": 6.0,
        "k": 0.13,
        "cte": 68.0,
        "maxT": 55.0,
        "procT": 180.0,
        "elec": "I",
        "costLo": 2.0,
        "costHi": 4.5,
        "source": "Fermentation of plant starches (corn/cassava) polymerized to PLA (NatureWorks Ingeo)",
        "moist": "M",
        "uv": "M",
        "chem": "F",
        "tough": "L",
        "ductile": False,
        "note": "100% bio-based compostable thermoplastic. Low heat deflection temperature (Tg ~58°C) limits warm applications.",
        "nu": 0.36,
        "color": "#e8dfc4",
        "astm": "ASTM D638, ASTM D6400"
    },
    {
        "id": "cotton",
        "name": "Cotton Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.54,
        "E": 6.0,
        "ts": 400.0,
        "elong": 7.0,
        "k": 0.04,
        "cte": 8.0,
        "maxT": 150.0,
        "procT": None,
        "elec": "I",
        "costLo": 1.5,
        "costHi": 3.0,
        "source": "Ginned from Gossypium seed bolls",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Cellulosic seed hair fiber; high elongation and softness, used in low-load biocomposites.",
        "nu": 0.30,
        "color": "#f2ede1",
        "astm": "ASTM D3822"
    },
    {
        "id": "bamboo",
        "name": "Bamboo Fibre",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.25,
        "E": 30.0,
        "ts": 500.0,
        "elong": 2.0,
        "k": 0.03,
        "cte": 8.0,
        "maxT": 200.0,
        "procT": None,
        "elec": "I",
        "costLo": 1.0,
        "costHi": 2.0,
        "source": "Steam-exploded from bamboo culms",
        "moist": "H",
        "uv": "H",
        "chem": "P",
        "tough": "M",
        "ductile": False,
        "note": "Fastest-growing woody plant. Good specific stiffness for sustainable building panels.",
        "nu": 0.30,
        "color": "#cbb97a",
        "astm": "ASTM D3822"
    },
    {
        "id": "silk",
        "name": "Silk Fibre (Bombyx mori)",
        "cat": "natfiber",
        "matrix": False,
        "reinf": True,
        "rho": 1.30,
        "E": 15.0,
        "ts": 600.0,
        "elong": 20.0,
        "k": 0.05,
        "cte": 8.0,
        "maxT": 150.0,
        "procT": None,
        "elec": "I",
        "costLo": 30.0,
        "costHi": 80.0,
        "source": "Reeled cocoon filament of silkworm",
        "moist": "M",
        "uv": "H",
        "chem": "F",
        "tough": "H",
        "ductile": False,
        "note": "Natural protein fiber with exceptional combination of tensile strength and 20% elongation.",
        "nu": 0.30,
        "color": "#f0ead9",
        "astm": "ASTM D3822"
    },
    {
        "id": "natrubber",
        "name": "Natural Rubber (Hevea)",
        "cat": "natpoly",
        "matrix": True,
        "reinf": False,
        "rho": 0.92,
        "E": 0.02,
        "ts": 25.0,
        "elong": 600.0,
        "k": 0.13,
        "cte": 200.0,
        "maxT": 80.0,
        "procT": 160.0,
        "elec": "I",
        "costLo": 1.5,
        "costHi": 2.5,
        "source": "Latex tapped from Hevea brasiliensis trees",
        "moist": "L",
        "uv": "H",
        "chem": "P",
        "tough": "H",
        "ductile": True,
        "note": "Elastomer matrix used with steel and textile cords in tyres.",
        "nu": 0.49,
        "color": "#8a5a34",
        "astm": "ASTM D412, ASTM D297"
    },

    # =========================================================================
    # 11. BASE ELEMENTS & ALLOY CONSTITUENTS
    # =========================================================================
    {
        "id": "al",
        "name": "Pure Aluminum (1100)",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 2.70,
        "E": 69.0,
        "ts": 90.0,
        "elong": 40.0,
        "k": 237.0,
        "cte": 23.1,
        "maxT": 200.0,
        "procT": 660.0,
        "elec": "C",
        "costLo": 2.0,
        "costHi": 3.0,
        "source": "Bauxite ore refined via Hall–Héroult electrolysis process",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "High electrical and thermal conductivity; soft in pure form.",
        "nu": 0.33,
        "color": "#c9cdd0",
        "astm": "ASTM E8/E8M, ASTM B311"
    },
    {
        "id": "fe",
        "name": "Pure Iron",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 7.87,
        "E": 211.0,
        "ts": 250.0,
        "elong": 30.0,
        "k": 80.0,
        "cte": 11.8,
        "maxT": 500.0,
        "procT": 1538.0,
        "elec": "C",
        "costLo": 0.5,
        "costHi": 1.0,
        "source": "Hematite/magnetite ore reduced in blast furnace",
        "moist": "H",
        "uv": "L",
        "chem": "P",
        "tough": "H",
        "ductile": True,
        "note": "Base constituent for carbon and alloy steels.",
        "nu": 0.29,
        "color": "#8c8a86",
        "astm": "ASTM E8/E8M, ASTM E1268"
    },
    {
        "id": "ti",
        "name": "Pure Titanium (Grade 2)",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 4.51,
        "E": 105.0,
        "ts": 345.0,
        "elong": 20.0,
        "k": 22.0,
        "cte": 8.6,
        "maxT": 350.0,
        "procT": 1668.0,
        "elec": "C",
        "costLo": 8.0,
        "costHi": 15.0,
        "source": "Ilmenite/rutile ore processed via Kroll process",
        "moist": "L",
        "uv": "L",
        "chem": "E",
        "tough": "H",
        "ductile": True,
        "note": "Commercially pure titanium with outstanding corrosion resistance.",
        "nu": 0.34,
        "color": "#9a9b9d",
        "astm": "ASTM B265, ASTM E8/E8M"
    },
    {
        "id": "cu",
        "name": "Copper (OFHC C10100)",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 8.96,
        "E": 117.0,
        "ts": 220.0,
        "elong": 45.0,
        "k": 401.0,
        "cte": 16.5,
        "maxT": 300.0,
        "procT": 1085.0,
        "elec": "C",
        "costLo": 8.0,
        "costHi": 10.0,
        "source": "Oxygen-free high conductivity copper smelted and electro-refined",
        "moist": "L",
        "uv": "L",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Best electrical and thermal conductor among structural engineering metals.",
        "nu": 0.34,
        "color": "#c77f4a",
        "astm": "ASTM E8/E8M, ASTM B193"
    },
    {
        "id": "ni",
        "name": "Nickel (Pure Ni 200)",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 8.90,
        "E": 200.0,
        "ts": 460.0,
        "elong": 40.0,
        "k": 70.0,
        "cte": 13.3,
        "maxT": 600.0,
        "procT": 1455.0,
        "elec": "C",
        "costLo": 15.0,
        "costHi": 24.0,
        "source": "Sulfide ore smelting followed by Mond carbonyl purification",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Base constituent for high-temperature superalloys.",
        "nu": 0.31,
        "color": "#b9b6ae",
        "astm": "ASTM B160, ASTM E8/E8M"
    },
    {
        "id": "w",
        "name": "Tungsten",
        "cat": "element",
        "matrix": False,
        "reinf": True,
        "rho": 19.30,
        "E": 411.0,
        "ts": 980.0,
        "elong": 2.0,
        "k": 173.0,
        "cte": 4.5,
        "maxT": 1200.0,
        "procT": 3422.0,
        "elec": "C",
        "costLo": 30.0,
        "costHi": 45.0,
        "source": "Wolframite/scheelite ore, hydrogen-reduced to powder",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Highest melting point of all metals (3422°C); extreme density for radiation shielding and kinetic penetrators.",
        "nu": 0.28,
        "color": "#5c5d5f",
        "astm": "ASTM E8/E8M, ASTM B760"
    },
    {
        "id": "mg",
        "name": "Magnesium",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 1.74,
        "E": 45.0,
        "ts": 160.0,
        "elong": 10.0,
        "k": 156.0,
        "cte": 26.0,
        "maxT": 150.0,
        "procT": 650.0,
        "elec": "C",
        "costLo": 3.0,
        "costHi": 5.0,
        "source": "Pidgeon thermal reduction or brine electrolysis",
        "moist": "H",
        "uv": "L",
        "chem": "P",
        "tough": "M",
        "ductile": True,
        "note": "Lightest structural metal. High specific damping capacity.",
        "nu": 0.35,
        "color": "#c8c9c4",
        "astm": "ASTM E8/E8M, ASTM B94"
    },
    {
        "id": "steel",
        "name": "Mild Structural Steel (A36)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 7.85,
        "E": 200.0,
        "ts": 420.0,
        "elong": 25.0,
        "k": 50.0,
        "cte": 12.0,
        "maxT": 400.0,
        "procT": 1480.0,
        "elec": "C",
        "costLo": 0.6,
        "costHi": 1.0,
        "source": "Basic oxygen furnace / electric arc furnace steelmaking",
        "moist": "H",
        "uv": "L",
        "chem": "P",
        "tough": "H",
        "ductile": True,
        "note": "Universal structural benchmark for civil and mechanical engineering.",
        "nu": 0.29,
        "color": "#5a5c5e",
        "astm": "ASTM A36, ASTM E8/E8M"
    },
    {
        "id": "ss304",
        "name": "Stainless Steel 304",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.00,
        "E": 193.0,
        "ts": 550.0,
        "elong": 45.0,
        "k": 16.0,
        "cte": 17.3,
        "maxT": 870.0,
        "procT": 1450.0,
        "elec": "C",
        "costLo": 2.0,
        "costHi": 4.0,
        "source": "18Cr-8Ni austenitic stainless steel",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "General purpose corrosion-resistant austenitic alloy.",
        "nu": 0.29,
        "color": "#c6c9cb",
        "astm": "ASTM A276, ASTM E8/E8M"
    },
    {
        "id": "al6061",
        "name": "Aluminium Alloy 6061-T6",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 2.70,
        "E": 69.0,
        "ts": 310.0,
        "elong": 12.0,
        "k": 167.0,
        "cte": 23.6,
        "maxT": 300.0,
        "procT": 660.0,
        "elec": "C",
        "costLo": 3.0,
        "costHi": 5.0,
        "source": "Precipitation-hardened Al-Mg-Si wrought alloy",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Most common metal-matrix composite base (e.g. Al6061/SiC particulate brake rotors).",
        "nu": 0.33,
        "color": "#b9bcbd",
        "astm": "ASTM B221, ASTM E8/E8M"
    },
    {
        "id": "brass",
        "name": "Cartridge Brass (C26000)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.53,
        "E": 110.0,
        "ts": 340.0,
        "elong": 40.0,
        "k": 115.0,
        "cte": 19.9,
        "maxT": 200.0,
        "procT": 950.0,
        "elec": "C",
        "costLo": 5.0,
        "costHi": 7.5,
        "source": "70Cu-30Zn alloy",
        "moist": "M",
        "uv": "L",
        "chem": "F",
        "tough": "H",
        "ductile": True,
        "note": "Excellent cold-working ductility and acoustic resonance.",
        "nu": 0.34,
        "color": "#c9a24b",
        "astm": "ASTM B36, ASTM E8/E8M"
    },
    {
        "id": "bronze",
        "name": "Phosphor Bronze (C51000)",
        "cat": "metal",
        "matrix": True,
        "reinf": False,
        "rho": 8.86,
        "E": 110.0,
        "ts": 380.0,
        "elong": 20.0,
        "k": 70.0,
        "cte": 17.8,
        "maxT": 250.0,
        "procT": 950.0,
        "elec": "C",
        "costLo": 6.5,
        "costHi": 9.5,
        "source": "Copper alloyed with tin and deoxidized with phosphorus",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Bearing alloy; self-lubricating bronze/graphite composites are standard.",
        "nu": 0.34,
        "color": "#a8763f",
        "astm": "ASTM B103, ASTM B505"
    },
    {
        "id": "cr",
        "name": "Pure Chromium",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 7.19,
        "E": 279.0,
        "ts": 290.0,
        "elong": 0.5,
        "k": 94.0,
        "cte": 4.9,
        "maxT": 1500.0,
        "procT": 1907.0,
        "elec": "C",
        "costLo": 8.0,
        "costHi": 12.0,
        "source": "Chromite ore, reduced by aluminothermy or electrolysis",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "L",
        "ductile": False,
        "note": "Extremely hard and corrosion-resistant. Low CTE makes it useful in thermal-barrier coatings.",
        "nu": 0.21,
        "color": "#8a8b8d",
        "astm": "ASTM E8/E8M"
    },
    {
        "id": "mo",
        "name": "Molybdenum",
        "cat": "element",
        "matrix": False,
        "reinf": True,
        "rho": 10.28,
        "E": 329.0,
        "ts": 550.0,
        "elong": 30.0,
        "k": 138.0,
        "cte": 4.8,
        "maxT": 1500.0,
        "procT": 2623.0,
        "elec": "C",
        "costLo": 20.0,
        "costHi": 35.0,
        "source": "Molybdenite ore, roasted and hydrogen-reduced",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "M",
        "ductile": True,
        "note": "High melting point and low CTE; Mo/Cu heat-spreader composites for power electronics.",
        "nu": 0.31,
        "color": "#7a7b7d",
        "astm": "ASTM B387, ASTM E8/E8M"
    },
    {
        "id": "zr",
        "name": "Zirconium",
        "cat": "element",
        "matrix": True,
        "reinf": True,
        "rho": 6.52,
        "E": 68.0,
        "ts": 330.0,
        "elong": 32.0,
        "k": 23.0,
        "cte": 5.7,
        "maxT": 400.0,
        "procT": 1855.0,
        "elec": "C",
        "costLo": 30.0,
        "costHi": 50.0,
        "source": "Zircon sand, chlorination and Kroll reduction",
        "moist": "L",
        "uv": "L",
        "chem": "G",
        "tough": "H",
        "ductile": True,
        "note": "Nuclear fuel cladding due to exceptionally low neutron absorption cross-section.",
        "nu": 0.34,
        "color": "#b0b1b2",
        "astm": "ASTM B493, ASTM E8/E8M"
    },
    {
        "id": "corticalbone",
        "name": "Cortical Bone (Dense Bio-Composite)",
        "cat": "bio",
        "matrix": False,
        "reinf": True,
        "rho": 1.85,
        "E": 20.0,
        "ts": 150.0,
        "elong": 2.5,
        "k": 0.56,
        "cte": 12.0,
        "maxT": 70.0,
        "procT": None,
        "elec": "I",
        "costLo": 10.0,
        "costHi": 50.0,
        "source": "Dense outer shell of mammalian long bone (~70% hydroxyapatite, ~30% collagen)",
        "moist": "M",
        "uv": "L",
        "chem": "F",
        "tough": "H",
        "ductile": False,
        "note": "Nature's own ceramic-polymer composite with exceptional fatigue resistance and fracture toughness.",
        "nu": 0.30,
        "color": "#f5f0e4",
        "astm": "ASTM F1839 (bone test specimens)"
    },
    {
        "id": "nacre",
        "name": "Nacre (Mother of Pearl)",
        "cat": "bio",
        "matrix": False,
        "reinf": True,
        "rho": 2.78,
        "E": 70.0,
        "ts": 140.0,
        "elong": 1.0,
        "k": 1.5,
        "cte": 8.0,
        "maxT": 300.0,
        "procT": None,
        "elec": "I",
        "costLo": 5.0,
        "costHi": 20.0,
        "source": "Mollusc shell aragonite CaCO3 platelets in protein matrix",
        "moist": "L",
        "uv": "L",
        "chem": "F",
        "tough": "H",
        "ductile": False,
        "note": "3000x tougher than mineral aragonite alone due to brick-and-mortar hierarchical architecture.",
        "nu": 0.23,
        "color": "#e8e0d8",
        "astm": "ASTM C1161 analogue"
    },
    {
        "id": "spidersilk",
        "name": "Spider Dragline Silk (Major Ampullate)",
        "cat": "bio",
        "matrix": False,
        "reinf": True,
        "rho": 1.31,
        "E": 13.0,
        "ts": 1400.0,
        "elong": 30.0,
        "k": 0.10,
        "cte": 40.0,
        "maxT": 250.0,
        "procT": None,
        "elec": "I",
        "costLo": 1000.0,
        "costHi": 5000.0,
        "source": "Recombinant spider dragline silk protein filament",
        "moist": "M",
        "uv": "H",
        "chem": "F",
        "tough": "H",
        "ductile": False,
        "note": "Toughness ~160 MJ/m³ — exceeds Kevlar by ~3x due to beta-sheet nanocrystals in amorphous matrix.",
        "nu": 0.30,
        "color": "#e8e0c0",
        "astm": "ASTM D3822 analogue"
    }
]

SEED_HARDENERS: List[Dict[str, Any]] = [
    # Epoxy Systems
    {
        "id": "teta",
        "matrix_id": "epoxy",
        "name": "Triethylenetetramine (TETA) — Aliphatic Amine",
        "ratio": "100:12 by weight",
        "cureTemp": 25.0,
        "postCure": 80.0,
        "tgShift": -10.0,
        "costBump": 0.6,
        "note": "Room-temperature cure, fast pot life (~20 min). Tough but lower heat deflection."
    },
    {
        "id": "ipda",
        "matrix_id": "epoxy",
        "name": "Isophorone Diamine (IPDA) — Cycloaliphatic Amine",
        "ratio": "100:30 by weight",
        "cureTemp": 25.0,
        "postCure": 120.0,
        "tgShift": 15.0,
        "costBump": 1.4,
        "note": "Slower cure, excellent UV and weathering resistance, higher usable temperature."
    },
    {
        "id": "anhydride",
        "matrix_id": "epoxy",
        "name": "Methyl Tetrahydrophthalic Anhydride (MTHPA)",
        "ratio": "100:85 by weight",
        "cureTemp": 120.0,
        "postCure": 160.0,
        "tgShift": 30.0,
        "costBump": 1.0,
        "note": "Requires oven cure. Maximum glass transition temperature (Tg > 150°C) and supreme electrical properties."
    },
    {
        "id": "dds_amine",
        "matrix_id": "epoxy_cycom",
        "name": "4,4'-Diaminodiphenyl Sulfone (DDS) Aromatic Amine",
        "ratio": "100:33 by weight",
        "cureTemp": 180.0,
        "postCure": 200.0,
        "tgShift": 25.0,
        "costBump": 3.0,
        "note": "Aerospace autoclave cure standard. High Tg (180°C+) and outstanding hot/wet retention."
    },
    # Polyester Systems
    {
        "id": "mekp",
        "matrix_id": "polyester",
        "name": "MEKP (Methyl Ethyl Ketone Peroxide) + Cobalt Octoate",
        "ratio": "1.5–2.0 phr",
        "cureTemp": 20.0,
        "postCure": 60.0,
        "tgShift": 0.0,
        "costBump": 0.3,
        "note": "Standard room-temperature radical initiator system for open-mold hand lay-up."
    },
    # Vinyl Ester Systems
    {
        "id": "mekp_ve",
        "matrix_id": "vinylester",
        "name": "MEKP-925H + Dimethylaniline Accelerator",
        "ratio": "1.25–1.5 phr",
        "cureTemp": 20.0,
        "postCure": 80.0,
        "tgShift": 0.0,
        "costBump": 0.3,
        "note": "Formulated for vinyl ester's methacrylate end-groups; excellent chemical barrier."
    },
    # Phenolic Systems
    {
        "id": "hexamine",
        "matrix_id": "phenolic",
        "name": "Hexamethylenetetramine (Hexamine Novolac Hardener)",
        "ratio": "8–12 phr",
        "cureTemp": 150.0,
        "postCure": 180.0,
        "tgShift": 0.0,
        "costBump": 0.4,
        "note": "Releases water and ammonia during cure; requires vented heated press."
    },
    # BMI Systems
    {
        "id": "bmi_catalyst",
        "matrix_id": "bmi",
        "name": "Diallyl Bisphenol A (DABPA) Coreactant",
        "ratio": "100:85 by weight",
        "cureTemp": 190.0,
        "postCure": 240.0,
        "tgShift": 20.0,
        "costBump": 2.5,
        "note": "Copolymerizes via ene-reaction to yield void-free, ultra-high Tg (260°C) laminates."
    },
    # Cyanate Ester Systems
    {
        "id": "cyest_cat",
        "matrix_id": "cyest",
        "name": "Copper Acetylacetonate + Nonylphenol Catalyst",
        "ratio": "0.1–0.5 phr",
        "cureTemp": 180.0,
        "postCure": 220.0,
        "tgShift": 15.0,
        "costBump": 1.5,
        "note": "Cyclotrimerization catalyst forming sym-triazine rings with ultra-low dielectric constant."
    },
    # Polyurethane
    {
        "id": "mdi",
        "matrix_id": "pu",
        "name": "MDI (Diphenylmethane Diisocyanate)",
        "ratio": "~100:45 by weight",
        "cureTemp": 25.0,
        "postCure": 80.0,
        "tgShift": 0.0,
        "costBump": 1.2,
        "note": "Standard rigid cast/foam PU isocyanate with fast reactivity."
    },
    # Natural Rubber
    {
        "id": "sulfur",
        "matrix_id": "natrubber",
        "name": "Sulfur + Accelerator (Vulcanization)",
        "ratio": "2–3 phr sulfur",
        "cureTemp": 150.0,
        "postCure": 160.0,
        "tgShift": 20.0,
        "costBump": 0.2,
        "note": "Classic vulcanization crosslinking rubber, dramatically raising tensile strength and elasticity."
    },
    # Silicone
    {
        "id": "pt_cat",
        "matrix_id": "silicone",
        "name": "Platinum Catalyst (Addition Cure)",
        "ratio": "~10:1 base:catalyst",
        "cureTemp": 25.0,
        "postCure": 100.0,
        "tgShift": 0.0,
        "costBump": 2.0,
        "note": "Clean addition cure with no by-products; medical and food-contact compatible."
    }
]


def seed_database(db):
    """Populates the database with initial materials and hardeners if empty."""
    from backend.models import Material, Hardener

    existing_count = db.query(Material).count()
    if existing_count == 0:
        for m_data in SEED_MATERIALS:
            db.add(Material(**m_data))
        for h_data in SEED_HARDENERS:
            db.add(Hardener(**h_data))
        db.commit()
        print(f"[Seed] Successfully seeded {len(SEED_MATERIALS)} materials and {len(SEED_HARDENERS)} hardeners.")
    else:
        existing_ids = {m[0] for m in db.query(Material.id).all()}
        added = 0
        for m_data in SEED_MATERIALS:
            if m_data["id"] not in existing_ids:
                db.add(Material(**m_data))
                added += 1
        existing_h_ids = {h[0] for h in db.query(Hardener.id).all()}
        for h_data in SEED_HARDENERS:
            if h_data["id"] not in existing_h_ids:
                db.add(Hardener(**h_data))
        if added > 0:
            db.commit()
            print(f"[Seed] Added {added} new materials to existing database.")

